/* eslint-disable no-undef */
/* eslint-disable @typescript-eslint/no-var-requires */
const { withAppDelegate } = require('@expo/config-plugins');
const { INDEX_ZERO, OFFSET_ONE } = require('constants/AppConstants');

const withRNGoogleMapsIOS = (config) => {
    return withAppDelegate(
        config,
        (config) => {
            const appDelegate = config.modResults;

            let contents = appDelegate.contents;
            /* This is the code generated by React native inside didFinishLaunchingWithOptions function; it might change in the future, look for your own anchor then */
            const headerIndex = contents.indexOf('@implementation AppDelegate');

            contents =
                contents.substring(INDEX_ZERO, headerIndex - OFFSET_ONE) +
                `\n#import <GoogleMaps/GoogleMaps.h>\n\n` +
                contents.substring(headerIndex);

            const injectionIndex = contents.indexOf('self.moduleName = @"main";');
            appDelegate.contents =
                contents.substring(INDEX_ZERO, injectionIndex) +
                `\n [GMSServices provideAPIKey:@"${process.env.GOOGLE_MAPS_API_KEY}"]; \n\n` +
                contents.substring(injectionIndex);

            return config;
        }
    );
};

module.exports = withRNGoogleMapsIOS